Add Control Page for sending commands
cornellrocketryteam/Ground-Software pull request #115
Opened 2024-10-09 21:31 UTC by AlyNat75

2024-10-09 21:31 UTC, AlyNat75 commented
* **#115** <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/115?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AlyNat75 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-10-09 21:55 UTC, maxslarsson requested changes

2024-10-09 21:55 UTC, maxslarsson commented on ground-server/src/components/actuation-box.tsx
> +          className={`mb-4 h-[100px] ${theme === "dark" ? "bg-gray-800" : "bg-gray-200"}`}>
Try not to do this, instead replace `${theme === "dark" ? "bg-gray-800" : "bg-gray-200"}` with `bg-gray-200 dark:bg-gray-800`. I think this was the cause of the flickering and wrong color during code review

2024-10-17 17:33 UTC, maxslarsson approved these changes
Looks great!

2024-10-17 17:34 UTC, merged

2024-10-17 17:34 UTC, AlyNat75 commented
### Merge activity

* **Oct 17, 1:34 PM EDT**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/115).