enabling grpc commands to actuate motor
cornellrocketryteam/Ground-Software pull request #135
Opened 2024-11-04 22:55 UTC by bwz5

2024-11-04 22:55 UTC, bwz5 commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/135?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#135** <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/135?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* **#128** <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/128?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#122** <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/122?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#84** <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/84?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#83** <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/83?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @bwz5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-05 03:26 UTC, ZachGarcia42 commented on fill/fill_station.cc
> +    WiringPiSetup();
Move this to the stepper motor object constructor

2024-11-05 03:27 UTC, ZachGarcia42 commented on fill/fill_station.cc
> +        if (request->qd_retract) {
Should be request->qd_retract() since it's a function call

2024-11-05 03:27 UTC, ZachGarcia42 requested changes
A few bugs found during end to end test

2024-11-06 20:48 UTC, ZachGarcia42 commented on fill/fill_station.cc
> +    WiringPiSetup();
Also I figured out that WiringPiSetupGpio() uses the standard gpio pin numbers which is why we were getting issues. Please update this to use WiringPiSetupGpio() and update the stepper motor pins to the correct ones (GPIO numbering) on the Pi Hat confluence page

2024-11-07 04:28 UTC, ZachGarcia42 approved these changes
Looks Great! Thanks for the fixes Ben!

2024-11-07 04:28 UTC, merged

2024-11-07 04:28 UTC, bwz5 commented
### Merge activity

* **Nov 6, 11:28 PM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/135).