Productionize ground server
cornellrocketryteam/Ground-Software pull request #148
Opened 2024-11-09 22:14 UTC by ZachGarcia42

2024-11-09 22:14 UTC, ZachGarcia42 commented
* **#148** <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/148?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ZachGarcia42 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-13 22:45 UTC, maxslarsson requested changes

2024-11-13 22:45 UTC, maxslarsson commented on ground-server/src/app/page.tsx
> +        console.error("Error creating WebSocket:", error);
```suggestion
```

2024-11-13 22:45 UTC, maxslarsson commented on ground-server/src/app/page.tsx
> +      try {
```suggestion
```

2024-11-13 22:45 UTC, maxslarsson commented on ground-server/src/app/page.tsx
> +            setTimeout(() => connect(fallbackUrl), 1000); //Retry after a delay
```suggestion
            connect(fallbackUrl);
```

2024-11-17 02:34 UTC, maxslarsson approved these changes

2024-11-17 02:35 UTC, merged

2024-11-17 02:35 UTC, ZachGarcia42 commented
### Merge activity

* **Nov 16, 9:35 PM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/148).