Modify control page based on code review discussion
cornellrocketryteam/Ground-Software pull request #155
Opened 2024-11-13 05:30 UTC by AlyNat75

2024-11-13 05:30 UTC, AlyNat75 commented
* **#155** <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/155?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @AlyNat75 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-13 15:56 UTC, ZachGarcia42 commented on ground-server/src/app/controls/page.tsx
> +            title="Rocket Name"
Update to "Andromeda?"

2024-11-13 15:59 UTC, ZachGarcia42 commented on ground-server/src/components/actuation-box.tsx
> +      // If switch is used and it's off, disable button actions
I don't think we want this. We want to be able to switch the Ball Valve's direction before we turn it back on

2024-11-13 16:07 UTC, ZachGarcia42 requested changes
Few small notes, but looks really good overall! Thanks Aly!

2024-11-13 16:26 UTC, ZachGarcia42 commented on ground-server/src/app/controls/page.tsx
> +        <h1 className="text-2xl font-bold mb-1 text-center">Rocket Commands</h1>
Could we add a rocket command for clearing the SD card?
This would also require adding a new command in the protobuf definition

2024-11-16 03:25 UTC, AlyNat75 commented
I fixed everything except adding the ability to clear the sd card, I can work on that after this weekend

2024-11-16 04:21 UTC, ZachGarcia42 approved these changes
Great! We can do the SD card in another PR

2024-11-16 04:21 UTC, merged

2024-11-16 04:22 UTC, AlyNat75 commented
### Merge activity

* **Nov 15, 11:22 PM EST**: A user merged this pull request with [Graphite](https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/155).