Add rocket fuel level widget for FDR
cornellrocketryteam/Ground-Software pull request #163
Opened 2024-11-16 04:46 UTC by maxslarsson

2024-11-16 04:46 UTC, maxslarsson commented
* **#163** <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/163?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/163?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-11-16 04:53 UTC, ZachGarcia42 reviewed
You should do FDR instead of this...

2024-11-16 05:03 UTC, ZachGarcia42 requested changes
The length of the green bar changes based on the width of the widget

2024-11-16 05:03 UTC, ZachGarcia42 commented on telemetry-proxy/telemetry_proxy
Why is this changed?

2024-11-16 05:07 UTC, ZachGarcia42 commented
> The length of the green bar changes based on the width of the widget

Wait it's random nevermind

2024-11-17 02:12 UTC, ZachGarcia42 approved these changes
Looks great! Super cool Widget!

2024-11-17 02:22 UTC, maxslarsson commented
### Merge activity

* **Nov 16, 9:22 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/163).

2024-11-17 02:22 UTC, merged