Implement Conops MVP
cornellrocketryteam/Ground-Software pull request #176
Opened 2024-12-08 06:48 UTC by AlyNat75

2024-12-08 06:48 UTC, AlyNat75 commented
* **#176** <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/176?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈 <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/176?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.
<!-- Current dependencies on/for this PR: -->

2024-12-09 15:19 UTC, ZachGarcia42 requested changes
So fairly major bug here: The Websocket connection for receiving and requesting telemetry is only open on the telemetry page, and closes when going to the Controls or Conops pages. You'll need to probably just open a new websocket on the Conops pages to receive and display telemetry

2024-12-09 15:25 UTC, ZachGarcia42 requested changes

2024-12-09 15:25 UTC, ZachGarcia42 commented on ground-server/src/app/conops/page6/page.tsx
> +                label: "Arm",
Change to Ignite and Ignited I think

2024-12-09 15:25 UTC, ZachGarcia42 commented on ground-server/src/app/conops/page6/page.tsx
> +                    {"Next Page"}
Add previous page buttons

2024-12-09 15:25 UTC, ZachGarcia42 commented on ground-server/src/app/conops/page7/page.tsx
> +import { auth } from "@/app/auth";
add next page that forwards to telemetry

2025-01-19 01:23 UTC, ZachGarcia42 approved these changes
Max changed websocket behavior, so all good now!

2025-01-19 01:23 UTC, ZachGarcia42 commented
### Merge activity

* **Jan 18, 8:23 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/176).

2025-01-19 01:42 UTC, merged