Formatting sensors/actuators directories and adding necessary files.
cornellrocketryteam/Ground-Software pull request #55
Opened 2024-09-25 21:55 UTC by bwz5

2024-09-25 21:55 UTC, bwz5 commented
* **#55** <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/55?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @bwz5 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-26 15:36 UTC, ZachGarcia42 commented on actuators/BUILD
> +        "//ground:__subpackages__",
We should delete all references to //ground now that that directory is gone

2024-09-26 15:37 UTC, ZachGarcia42 commented on fill/telemetry_reader.cc
> +}
Please revert this extraneous space for cleanliness

2024-09-26 15:37 UTC, ZachGarcia42 commented on sensors/BUILD
> +        "//ground:__subpackages__",
more //ground references here

2024-09-26 15:38 UTC, ZachGarcia42 commented on sensors/ptd.cc
>  float Ducer::Read() {
Should also change Ducer::Read if we're making this a PTD library

2024-09-26 15:39 UTC, ZachGarcia42 requested changes
Added some comments, but looks really good overall!

2024-09-26 15:56 UTC, ZachGarcia42 commented on fill/telemetry_reader.cc
> +}
Still see this space

2024-09-26 17:58 UTC, ZachGarcia42 approved these changes
Thanks for the work!

2024-09-26 17:58 UTC, merged

2024-09-26 17:58 UTC, bwz5 commented
### Merge activity

* **Sep 26, 1:58 PM EDT**: @bwz5 merged this pull request with [Graphite](https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/55).