Fix arm64 docker fill-station image build
cornellrocketryteam/Ground-Software pull request #67
Opened 2024-09-29 18:34 UTC by ZachGarcia42

2024-09-29 18:34 UTC, ZachGarcia42 commented
* **#67** <a href="https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/67?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ZachGarcia42 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-09-29 19:01 UTC, ZachGarcia42 commented
This works when running in Qemu. Will test on pi 4 shortly

2024-09-29 19:23 UTC, ZachGarcia42 commented
> This works when running in Qemu. Will test on pi 4 shortly

Confirmed working on the Pi!

2024-09-30 16:00 UTC, maxslarsson requested changes

2024-09-30 16:00 UTC, maxslarsson commented on fill/GithubDockerfile
> +# FROM --platform=linux/arm/v7 arm32v7/ubuntu:22.04 AS run
Should we remove this comment?

2024-09-30 16:00 UTC, maxslarsson commented on fill/GithubDockerfile
> +# ENTRYPOINT [ "tail", "-f", "/dev/null" ]
Same with this one?

2024-09-30 16:36 UTC, ZachGarcia42 commented
Removed extra lines

2024-09-30 17:26 UTC, maxslarsson approved these changes

2024-09-30 17:27 UTC, maxslarsson requested changes

2024-09-30 17:27 UTC, maxslarsson commented on telemetry-proxy/telemetry_proxy
Do we want to commit the executable?

2024-09-30 17:27 UTC, ZachGarcia42 commented
### Merge activity

* **Sep 30, 1:27 PM EDT**: [Graphite](https://app.graphite.dev/github/pr/cornellrocketryteam/Ground-Software/67) couldn't merge this PR because it failed for an unknown reason (Changes have been requested by reviewers on this PR).

2024-09-30 17:27 UTC, maxslarsson commented
My bad I approved and then I saw that the executable has been commited as well.

2024-09-30 17:42 UTC, ZachGarcia42 commented on telemetry-proxy/telemetry_proxy
No, we do not. This isn't matching what my local instance shows though :(

2024-09-30 17:44 UTC, ZachGarcia42 commented on telemetry-proxy/telemetry_proxy
Ok, restarting VSCode seemed to make it figure itself out

2024-09-30 17:48 UTC, maxslarsson approved these changes

2024-09-30 17:49 UTC, merged